name: Veracode Software Composition Analysis

on:
  schedule:
    - cron: '0 4 * * 3'

jobs:
  veracode_sca_task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Veracode SCA
        id: veracode-sca
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.15
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false
          debug: true
          allow-dirty: true
          recursive: true
          update_advisor: true