name: Veracode Software Composition Analysis

on: workflow_dispatch

jobs:
  veracode_sca_task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "8"
          distribution: "temurin"
          cache: "maven"
          settings-path: ${{ github.workspace }}

      - name: Run Veracode SCA
        id: veracode-sca
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.15
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false
          debug: true
          allow-dirty: true
          recursive: true

      - name: Display scan URL
        env:
          SCAN_URL: ${{ toJson(steps.veracode-sca.outputs.scan-url) }}
        run: |
          echo "View detailed report at: ${{ env.SCAN_URL }}"