name: Veracode Pipeline Scan And SARIF Upload

on: [workflow_dispatch, pull_request]

env:
  BUILD_ARTIFACT_NAME: maven-build

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact_name: maven-build

  pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: Veracode Pipeline Scan
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: get archive
        uses: actions/download-artifact@v6
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@esd-true
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          file: "verademo.war"
          veracode_policy_name: "Veracode Recommended Very High"
          debug: 1
          fail_build: false

      # - uses: actions/upload-artifact@v6
      #   with:
      #     name: Veracode Pipeline-Scan Results
      #     path: results.json

  results_to_sarif:
    needs: pipeline_scan
    runs-on: ubuntu-latest
    name: Import Pipeline Results to SARIF
    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: Get scan results
        uses: actions/download-artifact@v6
        with:
          name: "Veracode Pipeline-Scan Results"

      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: Veracode/veracode-pipeline-scan-results-to-sarif@v2.0.4
        with:
          results-json: filtered_results.json
          output-results-sarif: veracode-results.sarif
          source-base-path-1: "^com/:src/main/java/com/"
          source-base-path-2: "^WEB-INF:src/main/webapp/WEB-INF"
          repo_owner: ${{ github.repository_owner }}
          # repo_name: ${{ github.event.repository.name }}
          commitSHA: ${{ github.sha }}
          ref: ${{ github.ref }}
          githubToken: ${{ github.token }}

      - name: Upload SARIF
        id: upload
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: veracode-results.sarif
          category: pipeline-scan
