on:
  workflow_dispatch: 
    inputs:
      repository_owner: 
        description: 'repository_owner of original commit (provided by GitHub app via `github.event.client_payload.repository.owner`)'
        required: true
        type: string
      profile_name:
        required: true
        type: string
      default_runs_on:
        required: true
        type: string
      filter_mitigated_flaws:
        required: true
        type: string

jobs:
  veracode-policy-results:
    # needs: policy_scan
    runs-on: ${{ fromJSON(inputs.default_runs_on) }}
    container:
      image: veracode/api-signing
      env:
        VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
        VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
      options: --user=1001
    if: always()
    name: Filter unmitigated results
    steps:
      - name: Checkout script
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository_owner }}/veracode
          sparse-checkout: |
            /scripts/filter_policy_results.sh
          sparse-checkout-cone-mode: false
      - name: Get scan results
        run: |
          ls -laR .
          chmod +x scripts/filter_policy_results.sh
          mkdir -p /tmp/output
          ./scripts/filter_policy_results.sh "${{ inputs.profile_name }}" --filter "unmitigated_results" --output-file /tmp/output/policy_flaws.json
          ls -lr /tmp
        continue-on-error: true

      - name: Veracode Policy Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          # policy_flaws.json
          name: policy-flaws
          path: /tmp/output
          overwrite: true
        continue-on-error: true
